In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('all_seasons.csv')
df

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Dennis Rodman,CHI,36.0,198.12,99.790240,Southeastern Oklahoma State,USA,1986,2,...,5.7,16.1,3.1,16.1,0.186,0.323,0.100,0.479,0.113,1996-97
1,1,Dwayne Schintzius,LAC,28.0,215.90,117.933920,Florida,USA,1990,1,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
2,2,Earl Cureton,TOR,39.0,205.74,95.254320,Detroit Mercy,USA,1979,3,...,0.8,1.0,0.4,-2.1,0.105,0.102,0.103,0.376,0.148,1996-97
3,3,Ed O'Bannon,DAL,24.0,203.20,100.697424,UCLA,USA,1995,1,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,4,Ed Pinckney,MIA,34.0,205.74,108.862080,Villanova,USA,1985,1,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12300,12300,Markieff Morris,MIA,32.0,205.74,111.130040,Kansas,USA,2011,1,...,7.6,2.6,1.4,4.5,0.059,0.089,0.197,0.547,0.116,2021-22
12301,12301,Markelle Fultz,ORL,24.0,193.04,94.800728,Washington,USA,2017,1,...,10.8,2.7,5.5,-5.3,0.010,0.116,0.265,0.517,0.448,2021-22
12302,12302,Marcus Smart,BOS,28.0,193.04,99.790240,Oklahoma State,USA,2014,1,...,12.1,3.8,5.9,9.3,0.018,0.093,0.179,0.540,0.245,2021-22
12303,12303,Marcus Garrett,MIA,23.0,195.58,92.986360,Kansas,USA,Undrafted,Undrafted,...,1.1,1.9,0.6,5.8,0.072,0.108,0.086,0.280,0.069,2021-22
12304,12304,Micah Potter,DET,24.0,208.28,112.490816,Wisconsin,USA,Undrafted,Undrafted,...,4.0,3.0,0.0,-56.4,0.095,0.125,0.148,0.505,0.000,2021-22

In [8]:
dennis_rodman_team = list(set(df[df['player_name'] == "Shaquille O'Neal"]['team_abbreviation']))
dennis_rodman_team

['LAL', 'PHX', 'BOS', 'CLE', 'MIA']

In [17]:
boston_players = list(set(df[df['team_abbreviation'] == "BOS"]['player_name']))
#len(boston_players)
sorted(boston_players)

['Aaron Nesmith',
 'Abdel Nader',
 'Adrian Griffin',
 'Al Horford',
 'Al Jefferson',
 'Allan Ray',
 'Alton Lister',
 'Amir Johnson',
 'Andrew DeClercq',
 'Antoine Walker',
 'Aron Baynes',
 'Avery Bradley',
 'Bimbo Coles',
 'Brad Wanamaker',
 'Brandon Bass',
 'Brandon Hunter',
 'Brett Szabo',
 'Brian Scalabrine',
 'Brodric Thomas',
 'Bruce Bowen',
 'Bruno Sundov',
 'Bryant Stith',
 'CJ Miles',
 'Calbert Cheaney',
 'Carlos Arroyo',
 'Carsen Edwards',
 'Chris Babb',
 'Chris Carr',
 'Chris Herren',
 'Chris Johnson',
 'Chris Mihm',
 'Chris Wilcox',
 'Chucky Atkins',
 'Coty Clarke',
 'Courtney Lee',
 'DJ White',
 'Damon Jones',
 'Dan Dickau',
 'Dana Barros',
 'Daniel Theis',
 'Danny Fortson',
 'Darko Milicic',
 'David Wesley',
 'Dee Brown',
 'Delonte West',
 'Demetrius Jackson',
 'Derrick White',
 'Dino Radja',
 "Dontae' Jones",
 'Doug Overton',
 'Dwayne Jones',
 'Dwayne Schintzius',
 "E'Twaun Moore",
 'Eddie House',
 'Enes Freedom',
 'Enes Kanter',
 'Eric Riley',
 'Eric Williams',
 'Erick Strickland',
 'Evan Fournier',
 'Evan Turner',
 'Fab Melo',
 'Frank Brickowski',
 'Gabe Pruitt',
 'Gary Payton',
 'Gerald Green',
 'Gerald Wallace',
 'Gigi Datome',
 'Glen Davis',
 'Gordon Hayward',
 'Grant Long',
 'Grant Williams',
 'Greg Minor',
 'Greg Monroe',
 'Greg Stiemsma',
 'Guerschon Yabusele',
 'Henry Walker',
 'Isaiah Thomas',
 'J.R. Bremer',
 'J.R. Giddens',
 'JaJuan Johnson',
 'Jabari Bird',
 'Jabari Parker',
 'Jae Crowder',
 'James Posey',
 'James Young',
 'Jared Sullinger',
 'Jason Terry',
 'Javonte Green',
 'Jaylen Brown',
 'Jayson Tatum',
 'Jeff Green',
 "Jermaine O'Neal",
 'Jerome Moiso',
 'Jerryd Bayless',
 'Jiri Welsch',
 'Joe Johnson',
 'Joel Anthony',
 'Jonas Jerebko',
 'Jonathan Gibson',
 'Jordan Crawford',
 'Jordan Mickey',
 'Joseph Forte',
 'Jumaine Jones',
 'Justin Reed',
 'Juwan Morgan',
 'Kadeem Allen',
 'Kedrick Brown',
 'Keith Bogans',
 'Kelan Martin',
 'Kelly Olynyk',
 'Kemba Walker',
 'Kendrick Perkins',
 'Kenny Anderson',
 'Kevin Garnett',
 'Kevinn Pinkney',
 'Keyon Dooling',
 'Kris Humphries',
 'Kyrie Irving',
 'Leandro Barbosa',
 'Leon Powe',
 'Luke Kornet',
 'Malik Fitts',
 'Marcus Banks',
 'Marcus Landry',
 'Marcus Morris Sr.',
 'Marcus Smart',
 'Mark Blount',
 'Mark Bryant',
 'Marlon Garnett',
 'Marquis Daniels',
 'Marty Conlon',
 'Matt Ryan',
 'Michael Finley',
 'Michael Hawkins',
 'Michael Olowokandi',
 'Michael Stewart',
 'Mickael Pietrus',
 'Mikki Moore',
 'Milt Palacio',
 'Moses Brown',
 'Nate Driggers',
 'Nate Robinson',
 'Nenad Krstic',
 'Nik Stauskas',
 'Oliver Lafayette',
 'Orien Greene',
 'P.J. Brown',
 'PJ Dozier',
 'Paul Pierce',
 'Payton Pritchard',
 'Pervis Ellison',
 'Phil Pressey',
 'Popeye Jones',
 'RJ Hunter',
 'Raef LaFrentz',
 'Rajon Rondo',
 'Randy Brown',
 'Rasheed Wallace',
 'Ray Allen',
 'Reggie Hanson',
 'Rick Fox',
 'Ricky Davis',
 'Robert Williams III',
 'Rodney Rogers',
 'Romeo Langford',
 'Ron Mercer',
 'Ruben Wolkowyski',
 'Ryan Gomes',
 'Ryan Hollins',
 'Sam Cassell',
 'Sam Hauser',
 'Sasha Pavlovic',
 'Scot Pollard',
 'Sean Williams',
 'Sebastian Telfair',
 'Semi Ojeleye',
 'Shane Larkin',
 "Shaquille O'Neal",
 'Shavlik Randolph',
 'Shelden Williams',
 'Stephon Marbury',
 'Steve Hamer',
 'Tacko Fall',
 'Terrence Williams',
 'Terry Rozier',
 'Theo Ratliff',
 'Todd Day',
 'Tony Allen',
 'Tony Battie',
 'Tony Delk',
 'Travis Knight',
 'Tremont Waters',
 'Tristan Thompson',
 'Troy Murphy',
 'Tyler Zeller',
 'Tyus Edney',
 'Vander Blue',
 'Vin Baker',
 'Vincent Poirier',
 'Vitaly Potapenko',
 'Vitor Faverani',
 'Von Wafer',
 'Wally Szczerbiak',
 'Walter McCarty',
 'Wayne Turner',
 'Xavier Silas',
 'Zan Tabak']

In [22]:
shaq = set(df[df['player_name'] == "Shaquille O'Neal"]['team_abbreviation'])
print(shaq)
tatum  = set(df[df['player_name'] == "Jayson Tatum"]['team_abbreviation'])
print(tatum)

{'LAL', 'PHX', 'BOS', 'CLE', 'MIA'}
{'BOS'}

In [24]:
#name1 = input('Introduce el nombre:  ')
#name2 = input('Introduce el nombre:  ')

shaq = set(df[df['player_name'] == "Shaquille O'Neal"]['team_abbreviation'])
print(shaq)
tatum  = set(df[df['player_name'] == "Jayson Tatum"]['team_abbreviation'])
print(tatum)
equipos_comunes = shaq & tatum

# Verificar si hay elementos comunes
if equipos_comunes:
    print("Hay elementos comunes entre ambos conjuntos:", equipos_comunes)
else:
    print("No hay elementos comunes entre ambos conjuntos.")

{'LAL', 'PHX', 'BOS', 'CLE', 'MIA'}
{'BOS'}
Hay elementos comunes entre ambos conjuntos: {'BOS'}

In [28]:
name1 = input('Introduce el nombre:  ')
name2 = input('Introduce el nombre:  ')

shaq = set(df[df['player_name'] == name1]['team_abbreviation'])
tatum  = set(df[df['player_name'] == name2]['team_abbreviation'])

equipos_comunes = shaq & tatum

# Verificar si hay elementos comunes
if equipos_comunes:
    print("Hay elementos comunes entre ambos conjuntos:", equipos_comunes)
else:
    print("No hay elementos comunes entre ambos conjuntos.")

Introduce el nombre:  tatum
Introduce el nombre:  o'neal
No hay elementos comunes entre ambos conjuntos.

In [18]:
name = input('Introduce el nombre:  ')

first_r = ['BOS', 'CLE', 'PHX']
second_r = ['LAL', 'MIA', 'OKC']

teams = set(df[df['player_name'] == name]['team_abbreviation'])


for team in teams:
    if first_r[0] in teams and second_r[2] in teams:
        print('correcto')
        break
    else:
        print('incorrecto')
        break
    #if df['player_name']['team_abbreviation'] in team and df['player_name']['team_abbreviation'] in team:
 #   print(f'{primer_valor} and {segundo_valor}')

Introduce el nombre:  Shaquille O'Neal
incorrecto

In [ ]:
Shaquille O'Neal

In [ ]:
import random
equipos = ['ATL', 'BKN', 'BOS', 'CHA', 'CHH', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 
 'MIN', 'NJN', 'NOH', 'NOK', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'SEA', 'TOR', 'UTA', 'VAN', 'WAS']
#equipos = ['ATL', 'BKN', 'BOS', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 
 #'MIN', 'NJN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']

first_r = []
second_r = []
# CREC QUE POT TORNAR MATEIX NOMBRE 2 VEGADES, REPASSA    
rands = [random.randint(0, 36) for i in range(6) ] # if i not in rands SI FAIG ASO DARRERA, ME TORNA UN DE BUIT, FER FUNCIÓ
count = 0
for i in rands:
    count += 1
    if count <= 3:
        first_r.append(equipos[i])
    else:
        second_r.append(equipos[i])
print(first_r)
print(second_r)

name = input('Introduce el nombre del jugador:  ')
teams = set(df[df['player_name'] == name.title()]['team_abbreviation'])

num1 = int(input('Introduce un número: '))
num2 = int(input('Introduce un número: '))
for team in teams:
    
    if first_r[num1] in teams and second_r[num2] in teams:
        print('correcto')
        break
    else:
        print('incorrecto')
        break

['SAC', 'SAC', 'NOK']
['PHX', 'PHX', 'PHX']
Introduce el nombre del jugador:  devin booker
Devin Booker

In [64]:
player = list(set(df[df['player_name'] == "Shaquille O'Neal"]['team_abbreviation']))
player

['BOS']

In [76]:
# FALLA PERQUÈ TENC UN SET I NO UNA LLISTA CREC
import random
equipos = ['ATL', 'BKN', 'BOS', 'CHA', 'CHH', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 
 'MIN', 'NJN', 'NOH', 'NOK', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'SEA', 'TOR', 'UTA', 'VAN', 'WAS']
#equipos = ['ATL', 'BKN', 'BOS', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 
# 'MIN', 'NJN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']

first_r = []
second_r = []
rands = set()
while len(rands) < 6:
    rands.add(random.randint(0, 36))

# Si hay algún número repetido, generamos un reemplazo adicional
while len(rands) < 6:
    rands.add(random.randint(0, 36))


count = 0
for i in list(rands):
    count += 1
    if count <= 3:
        first_r.append(equipos[i])
    else:
        second_r.append(equipos[i])
print(first_r)
print(second_r)

name = input('Introduce el nombre del jugador:  ')

teams = set(df[df['player_name'] == name]['team_abbreviation'])

num1 = int(input('Introduce un número: '))
num2 = int(input('Introduce un número: '))
for team in teams:
    if first_r[num1] in teams and second_r[num2] in teams:
        print('correcto')
        break
    else:
        print('incorrecto')
        break

['HOU', 'IND', 'MEM']
['MIA', 'MIN', 'NOH']
Introduce el nombre del jugador:  kyle lowry
Introduce un número: 0
Introduce un número: 1